[default]
bootstrap.servers=broker:9092
# 'auto.offset.reset=earliest' to start reading from the beginning of
# the topic if no committed offsets exist.
auto.offset.reset=earliest

[monitor]
group.id=monitor

[communication]
group.id=communication

[crypto]
group.id=crypto

[battery-charge-control]
group.id=battery-charge-control

[complex]
group.id=complex

[emergency-stop]
group.id=emergency-stop

[gnss-navigation]
group.id=gnss-navigation

[internal-navigation]
group.id=internal-navigation

[message-processing]
group.id=message-processing

[movement-calculation]
group.id=movement-calculation

[movement-control]
group.id=movement-control

[route-control]
group.id=route-control

[sensors]
group.id=sensors

[servo]
group.id=servo

[task-execution-control]
group.id=task-execution-control

[telemetry-transmission]
group.id=telemetry-transmission